Repository hmcts/service-auth-provider-app, pull requests merged in 2019-07, with the labels that each got.

#149 Remove deleted vaults and generate secret in script
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  bin/set-secret-in-all-vaults
Labels: ns:rpe-service-auth-provider-pr-149

#148 Add et
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-148

#150 Add a microservice key for bulk-scan-ccd-event-handler-sample-app
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-150

#151 Remove deleted vaults from script
  bin/check-all-vaults-for-s2s-secret
Labels: ns:rpe-service-auth-provider-pr-151

#153 Add Employment Tribunals to values
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
Labels: ns:rpe-service-auth-provider-pr-153

#154 Upgrade to owasp 5
  build.gradle
Labels: ns:rpe-service-auth-provider-pr-154

#155 Update dependencies
  .dependabot/config.yml
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rpe-service-auth-provider-pr-155

#158 Add CODEOWNERS (platform engineering)
  CODEOWNERS
Labels: ns:rpe-service-auth-provider-pr-158

#159 feat: adding keys for access management apis
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-159

#160 add microservice key for bulk-scan-ccd-event-handler-sample-app tests
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-160

#162 adding xui-webapp
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-162
