Repository hmcts/service-auth-provider-app, pull requests merged in 2019-04, with the labels that each got.

#132 bump spring version
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:rpe-service-auth-provider-pr-132

#133 Refactoring preview configurations
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/requirements.yaml
  charts/rpe-service-auth-provider/values.aat.template.yaml
  charts/rpe-service-auth-provider/values.preview.template.yaml
  charts/rpe-service-auth-provider/values.yaml
Labels: ns:rpe-service-auth-provider-pr-133

#135 Fixing read me with latest file path
  README.md
Labels: ns:rpe-service-auth-provider-pr-135

#134 Add reference data api services
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-134

#136 Fix dep check
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:rpe-service-auth-provider-pr-136
