Repository hmcts/service-auth-provider-app, pull requests merged in 2019-09, with the labels that each got.

#185 Remove .git suffix for infra-approvals compatibility
  infrastructure/main.tf
Labels: ns:rpe-service-auth-provider-pr-185

#188 Bumping java chart
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/requirements.yaml
  charts/rpe-service-auth-provider/values.aat.template.yaml
  charts/rpe-service-auth-provider/values.preview.template.yaml
  charts/rpe-service-auth-provider/values.yaml
Labels: ns:rpe-service-auth-provider-pr-188

#194 cleanup ase
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:rpe-service-auth-provider-pr-194

#195 Update perftest.tfvars
  infrastructure/perftest.tfvars
Labels: ns:rpe-service-auth-provider-pr-195

#196 Add microservice key for Bulkscan payment processor
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-196
