Repository hmcts/service-auth-provider-app, pull requests merged in 2019-05, with the labels that each got.

#137 Add new secret definitions for CMC PAPI service
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-137

#138 Add JWTKey from secrets
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/requirements.yaml
  charts/rpe-service-auth-provider/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-138

#139 bump java chart version AB#109
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/requirements.yaml
Labels: ns:rpe-service-auth-provider-pr-139

#140 Set keys in perftest and ithc
  bin/check-all-vaults-for-s2s-secret
  bin/set-secret-in-all-vaults
Labels: ns:rpe-service-auth-provider-pr-140

#141 Fix CVE-2019-12086
  build.gradle
Labels: ns:rpe-service-auth-provider-pr-141

#142 Redeploy secrets
  infrastructure/main.tf
Labels: ns:rpe-service-auth-provider-pr-142

#143 Reload secrets.
  infrastructure/main.tf
Labels: ns:rpe-service-auth-provider-pr-143
