Repository hmcts/service-auth-provider-app, pull requests merged in 2019-08, with the labels that each got.

#167 update dependency
  build.gradle
Labels: ns:rpe-service-auth-provider-pr-167

#168 Adding ctsc-work-allocation microservice
  charts/rpe-service-auth-provider/values.yaml
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-service-auth-provider-pr-168

#170 Remove count change that never made it to master
  infrastructure/main.tf
Labels: ns:rpe-service-auth-provider-pr-170

#172 Update terraform provider
  infrastructure/main.tf
Labels: ns:rpe-service-auth-provider-pr-172

#173 Make test more flexible / reliable
  build.gradle
  src/test/java/uk/gov/hmcts/auth/provider/service/api/auth/JwtHS512ToolTest.java
Labels: ns:rpe-service-auth-provider-pr-173

#175 fix app insights version
  web.config
Labels: ns:rpe-service-auth-provider-pr-175

#176 fixing parameterized pipeline
  Jenkinsfile_parameterized
Labels: ns:rpe-service-auth-provider-pr-176

#177 Add MI identity
  infrastructure/.gitignore
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:rpe-service-auth-provider-pr-177

#180 Update perftest.tfvars
  infrastructure/perftest.tfvars
Labels: ns:rpe-service-auth-provider-pr-180
