Repository hmcts/service-auth-provider-app, pull requests merged in 2022-06, with the labels that each got.

#564 CVE fix and suppression to unblock the pipeline
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-564

#566 Update Chart.yaml
  charts/rpe-service-auth-provider/Chart.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-566

#567 DTSPO-8276 - Move CODEOWNERS file
  .github/CODEOWNERS
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-567
