Repository hmcts/service-auth-provider-app, pull requests merged in 2022-10, with the labels that each got.

#594 Some dependency updates
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-594

#599 ST-795-sptribs-case-api microservice has been added
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
  dependency-check-suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-599

#602 update read me
  README.md
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-602
