Repository hmcts/service-auth-provider-app, pull requests merged in 2023-09, with the labels that each got.

#803 Upgrade tomcat
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-803

#802 Add new idam-user-profile-bridge service
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-802

#807 Update build.gradle
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-807

#809 Update disposer-idam-user in values.yaml
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-809

#810 Update build.gradle
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-810
