Repository hmcts/service-auth-provider-app, pull requests merged in 2023-01, with the labels that each got.

#630 adding general application since its a new service
  charts/rpe-service-auth-provider/Chart.yaml
  charts/rpe-service-auth-provider/values.yaml
  dependency-check-suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-630

#639 Add renovate for appinsights upgrade
  .github/renovate.json
  Dockerfile
  dependency-check-suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-639

#640 Enable regex managers
  .github/renovate.json
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-640
