Repository hmcts/service-auth-provider-app, pull requests merged in 2023-03, with the labels that each got.

#664 Renovate: add terraform
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-664

#677 DTSPO-11734 - renovate - enable automerge
  .github/renovate.json
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-677

#665 TF, azurerm upgrade
  infrastructure/.terraform-version
  infrastructure/state.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-service-auth-provider-pr-665

#690 DTSPO-11734 - renovate - set schedule
  .github/renovate.json
Labels: ns:rpe, prd:rpe, rel:rpe-service-auth-provider-pr-690

#696 Renovate - use global presets
  .github/renovate.json
Labels: chore
